spring:
  thymeleaf:
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/blog?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: G!o2o3d4
  data:
    elasticsearch:
      cluster-nodes: localhost:9300
      cluster-name: my-application
      cluster_uuid: uDNGQLlsReuYtGV8j09xow
      node-name: node-1
  jpa:
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    com.pjb.blog: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
